# Generated by Django 4.2.5 on 2023-10-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_note_title_alter_syllabus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
