# Generated by Django 4.2.5 on 2023-10-08 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='namehash',
        ),
        migrations.CreateModel(
            name='HashTableNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namehash', models.BigIntegerField()),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.notes')),
            ],
        ),
    ]
