# Generated by Django 4.2.5 on 2023-10-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_hashtablenotes_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTableSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namehash', models.BigIntegerField()),
                ('syllabus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.syllabus')),
            ],
        ),
    ]
