# Generated by Django 4.2.5 on 2023-10-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hashtablesyllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtablenotes',
            old_name='notes',
            new_name='note',
        ),
    ]
